### PR TITLE
refactor: change button style

### PR DESCRIPTION
**Pull request by noviceCoder27**
Added styles to the button element
hulu

### CODE REVIEW

**Comment by kelvinparmar** [comment]
Hey @noviceCoder27 great work 
I just say that when you are working on any issue at that time first you to talk with maintainer because it's helps you and also help for the maintainer that this issue is assigned to someone so make sure next time

**Comment by noviceCoder27** [comment]
> Hey @noviceCoder27 great work I just say that when you are working on any issue at that time first you to talk with maintainer because it's helps you and also help for the maintainer that this issue is assigned to someone so make sure next time

Thanks for telling me this, I'm fairly new to open source so I'll keep this in mind next time when I want to work on any issue

**Comment by kelvinparmar** [comment]
@noviceCoder27 
Please connect with my social so will notify with more opportunities in open source

**Comment by noviceCoder27** [comment]
@kelvinparmar done

**Pull request merged**
